// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_NumberDelM.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package collatz;

public final class _NumberDelM extends Ice._ObjectDelM implements _NumberDel
{
}
