// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `MessagePrxHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package messagePasser;

public final class MessagePrxHolder
{
    public
    MessagePrxHolder()
    {
    }

    public
    MessagePrxHolder(MessagePrx value)
    {
        this.value = value;
    }

    public MessagePrx value;
}
